### ISSUE TITLE
Compiler Error with sdsl-lite 2.1.1 and above

### ISSUE THREAD

**Issue by Bradsol** [simongog/sdsl-lite#374]
I've been using SDSL-lite for some time using version 2.1 but recently attempted to upgrade to the latest release (as well as the latest git commit). In both cases I get the following error:

Build.o: In function `sdsl::int_vector<(unsigned char)0>::int_vector(unsigned long, unsigned long, unsigned char) [clone .constprop.408]':
Build.cc:(.text+0x25df): undefined reference to `sdsl::int_vector<(unsigned char)0>::width(unsigned char)'
Build.o: In function `sdsl::int_vector<(unsigned char)0>::swap(sdsl::int_vector<(unsigned char)0>&)':
Build.cc:(.text._ZN4sdsl10int_vectorILh0EE4swapERS1_[_ZN4sdsl10int_vectorILh0EE4swapERS1_]+0x30): undefined reference to `sdsl::int_vector<(unsigned char)0>::width(unsigned char)'
Build.cc:(.text._ZN4sdsl10int_vectorILh0EE4swapERS1_[_ZN4sdsl10int_vectorILh0EE4swapERS1_]+0x4d): undefined reference to `sdsl::int_vector<(unsigned char)0>::width(unsigned char)'
Build.o: In function `sdsl::rrr_vector<(unsigned short)255, sdsl::int_vector<(unsigned char)0>, (unsigned short)32>::rrr_vector(sdsl::int_vector<(unsigned char)1> const&)':
Build.cc:(.text._ZN4sdsl10rrr_vectorILt255ENS_10int_vectorILh0EEELt32EEC2ERKNS1_ILh1EEE[_ZN4sdsl10rrr_vectorILt255ENS_10int_vectorILh0EEELt32EEC5ERKNS1_ILh1EEE]+0x122): undefined reference to `sdsl::int_vector<(unsigned char)0>::width(unsigned char)'
Build.cc:(.text._ZN4sdsl10rrr_vectorILt255ENS_10int_vectorILh0EEELt32EEC2ERKNS1_ILh1EEE[_ZN4sdsl10rrr_vectorILt255ENS_10int_vectorILh0EEELt32EEC5ERKNS1_ILh1EEE]+0xbfd): undefined reference to `sdsl::int_vector<(unsigned char)0>::width(unsigned char)'
BF.o:BF.cc:(.text+0x96f7): more undefined references to `sdsl::int_vector<(unsigned char)0>::width(unsigned char)' follow
collect2: error: ld returned 1 exit status

What is odd about this is that sdsl::int_vector<(unsigned char)0>::width(unsigned char) registers as undefined in all versions but successfully compiles in version 2.1.

**Comment by mpetri** [comment]
what platform is this and how are you compiling things. I just checkout out a fresh copy of `sdsl-lite` and ran `install.sh` and compiled one of the examples:

```
[mpetri@umelb-168-918 ../sdsl-lite]$ cd examples/
[mpetri@umelb-168-918 ../examples]$ make fm-index.x
/usr/bin/c++ -std=c++11 -Wall -Wextra -DNDEBUG  -O3 -ffast-math -funroll-loops -msse4.2 -DHAVE_CXA_DEMANGLE -I/home/mpetri/include -L/home/mpetri/lib  -o fm-index.x fm-index.cpp -lsdsl -ldivsufsort -ldivsufsort64  
[mpetri@umelb-168-918 ../examples]$ 
```

seems to work ok?

**Comment by Bradsol** [comment]
This was compiled on a computer cluster running Ubuntu 14.04 using g++ version 4.9.1. 

However after running through the examples I think I see the problem. My Make file was not compiling with "-I/..../include" and was always finding the older locally installed version (and it would compile appropriately). However when using the newer versions there would be conflicts and it would fail to compile. I've corrected the Makefile to search for the appropriate -I and -L using pkg-config to prevent such desyncs in the future.
