### ISSUE TITLE
Build failed with error implicit instantiation of undefined template

### ISSUE THREAD

**Issue by le-van** [simongog/sdsl-lite#309]
I couldn't install sdsl because of below errors.
I'm using g++ 4.9.3 
Could you please check them?

Scanning dependencies of target sdsl
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bits.cpp.o
[  0%] Building CXX object lib/CMakeFiles/sdsl.dir/bp_support_algorithm.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/bp_support_algorithm.cpp:1:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/bp_support_algorithm.hpp:24:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 
      'seekpos' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: 
      overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
1 warning generated.
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_delta.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/coder_elias_delta.cpp:1:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/coder_elias_delta.hpp:24:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 'seekpos' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
1 warning generated.
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_elias_gamma.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/coder_elias_gamma.cpp:1:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/coder_elias_gamma.hpp:24:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 'seekpos' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
1 warning generated.
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/coder_fibonacci.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/coder_fibonacci.cpp:1:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/coder_fibonacci.hpp:24:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 'seekpos' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
1 warning generated.
[ 14%] Building CXX object lib/CMakeFiles/sdsl.dir/config.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/config.cpp:2:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 'seekpos' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
1 warning generated.
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_config.cpp.o
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_isa.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_isa.cpp:4:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_isa.hpp:24:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 'seekpos' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
1 warning generated.
[ 28%] Building CXX object lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/int_vector.hpp:26:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/util.hpp:25:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/sfstream.hpp:12:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/ram_filebuf.hpp:32:9: warning: 'seekpos' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        seekpos(pos_type sp,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/streambuf:190:22: note: overridden virtual function is here
    virtual pos_type seekpos(pos_type __sp,
                     ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:743:9: error: implicit instantiation of undefined template 'std::__1::array<std::__1::vector<std::__1::array<unsigned long long, 2>,
      std::__1::allocator<std::__1::array<unsigned long long, 2> > >, 2>'
        expand(const node_type& v,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:760:9: error: implicit instantiation of undefined template 'std::__1::array<std::__1::vector<std::__1::array<unsigned long long, 2>,
      std::__1::allocator<std::__1::array<unsigned long long, 2> > >, 2>'
        expand(const node_type& v,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:766:65: error: type 'std::__1::array<unsigned long long, 2>' does not provide a subscript operator
                auto sp_rank    = m_bv_rank(m_tree.bv_pos(v) + r[0]);
                                                               ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:767:65: error: type 'std::__1::array<unsigned long long, 2>' does not provide a subscript operator
                auto right_size = m_bv_rank(m_tree.bv_pos(v) + r[1] + 1)
                                                               ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:37: error: type 'std::__1::array<unsigned long long, 2>' does not provide a subscript operator
                auto left_size  = (r[1]-r[0]+1)-right_size;
                                   ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:769:42: error: type 'std::__1::array<unsigned long long, 2>' does not provide a subscript operator
                auto left_size  = (r[1]-r[0]+1)-right_size;
                                        ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:772:34: error: type 'std::__1::array<unsigned long long, 2>' does not provide a subscript operator
                auto left_sp  = r[0] - right_sp;
                                ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:777:20: error: implicit instantiation of undefined template 'std::__1::array<std::__1::vector<std::__1::array<unsigned long long,
      2>, std::__1::allocator<std::__1::array<unsigned long long, 2> > >, 2>'
            return {ranges, std::move(res)};
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:791:9: error: implicit instantiation of undefined template 'std::__1::array<std::__1::array<unsigned long long, 2>, 2>'
        expand(const node_type& v, const range_type& r) const {
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:33:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_huff.hpp:25:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:793:61: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
            auto sp_rank    = m_bv_rank(m_tree.bv_pos(v) + r[0]);
                                                           ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:794:61: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
            auto right_size = m_bv_rank(m_tree.bv_pos(v) + r[1] + 1)
                                                           ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:33: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
            auto left_size  = (r[1]-r[0]+1)-right_size;
                               ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:796:38: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
            auto left_size  = (r[1]-r[0]+1)-right_size;
                                    ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_pc.hpp:799:30: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
            auto left_sp  = r[0] - right_sp;
                            ~^~
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:73:34: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
                    return acc+(r[1]-r[0]+1);
                                ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:73:39: error: type 'const range_type' (aka 'const array<int_vector<>::size_type, 2>') does not provide a subscript operator
                    return acc+(r[1]-r[0]+1);
                                     ~^~
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:108:16: error: implicit instantiation of undefined template 'std::__1::array<unsigned long long, 2>'
    range_type r {{lb,rb}};
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:130:50: error: implicit instantiation of undefined template 'std::__1::array<unsigned long long, 2>'
_interval_symbols_rec(const t_wt& wt, range_type r,
                                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/lib/construct_lcp.cpp:6:
In file included from /Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/construct_lcp.hpp:34:
/Users/lehongvan/Documents/workspace/sdsl-lite/build/lib/../include/sdsl/wt_algorithm.hpp:552:22: error: implicit instantiation of undefined template 'std::__1::array<unsigned long long, 2>'
    sdsl::range_type initial_range = {x_i,x_j};
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:95:65: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[3]: *** [lib/CMakeFiles/sdsl.dir/construct_lcp.cpp.o] Error 1
make[2]: *** [lib/CMakeFiles/sdsl.dir/all] Error 2
make[1]: *** [lib/CMakeFiles/sdsl.dir/rule] Error 2
make: *** [sdsl] Error 2
ERROR: Build failed.

**Comment by karel-brinda** [comment]
I have the same problem with clang (Apple LLVM version 7.0.2 (clang-700.1.81)) but it works with g++ 5 (Homebrew gcc 5.3.0).

**Comment by le-van** [comment]
I upgraded to gcc 5.3.0 but still the same. Then I added #include <array> into sdsl-lite/include/sdsl/wt_pc.hpp and it worked.

**Comment by simongog** [comment]
Hi @le-van , so it was a missing include in wt_pc.hpp, which one is it? I still cannot reproduce the compile error and would appreciate a pull request with the the added include.

**Comment by le-van** [comment]
I updated the comment. The missing include was `array`.

**Comment by simongog** [comment]
Ok. Should work now.

**Comment by le-van** [comment]
Thank you @simongog

**Comment by karel-brinda** [comment]
@le-van @simongog Thanks, it works for me too.

@simongog Travis CI could prevent this type of problems. For example, in the Seqan project, they check compilation with Clang 3.5, 3.6, 3.7, GCC 4.9, 5.0, see https://github.com/seqan/seqan/blob/master/.travis.yml.

**Comment by simongog** [comment]
Hi Karel,
we also use a CI server (http://141.3.24.109:8080/job/sdsl-lite-pull-request/) to run test but by now we just use one version of Clang and GCC. It's a good idea to use Travis CI just for the compilation check!
